### ISSUE TITLE
Is it possible to triangulate using a sparsely used vector of points as a data source?

### ISSUE THREAD

**Issue by starseeker** [Kimbatt/detria#2]
Hi!  I recently found your detria implementation of CDT, and am interested in trying it out in our application.  We're currently using poly2tri (or more precisely a tweaked older version of poly2tri) to triangulate approximations of NURBS surfaces in 2D, and we rely on both holes and steiner points to get representative meshes.  Our input data is a series of C arrays holding polygon and point data.

Looking at the test cases, it appears that the steiner points are added into the set of points fed to setPoints, and the implication appears to be that any point in setPoints is either active in a polygon or is a steiner point - am I correct about that?

It's not a big problem if that's the case, it just means I need to copy the active set of points to their own vector before triangulation (which also gets the data into a form suitable for easy feeding to detria).  It would be nice to be able to directly use the data from the C arrays without copying, but that may be a bit too ambitious of me (even if I'm wrong about setPoints, my C++ template skills may not be up to making all the necessary connections to feed in everything as-is...)

**Comment by Kimbatt** [comment]
Hi,
You're right, currently you have to set all points at once, with a single setPoints call. Points which are not referenced by any polygon will automatically become steiner points.
I've also came to the conclusion that this might not be the most flexible way - just as you described, this only works if the points are in a contiguous memory location.
Currently, we have the PointAdapter class, which was supposed to handle conversions from user input, but I'm thinking of replacing it with a PointGetter class, which would work with your use case as well.

I'd change the setPoints function to also have another overload which takes a lambda function (or a functor), and the number of elements. The lambda function then could return the point for the given index, and you could implement a custom logic to retrieve it from a sparse vector. For example:
```cpp
std::vector<detria::PointD> outlinePoints = ...;
std::vector<detria::PointD> steinerPoints = ...;

uint32_t numOutlinePoints = uint32_t(outlinePoints.size());
uint32_t totalNumPoints = uint32_t(outlinePoints.size() + steinerPoints.size());

auto pointGetter = [&](uint32_t pointIndex)
{
    // pointIndex is in the range [0, totalNumPoints)

    if (pointIndex < numOutlinePoints)
    {
        // Point belongs to an outline
        return outlinePoints[pointIndex];
    }
    else
    {
        // Point is a steiner point
        return steinerPoints[pointIndex - numOutlinePoints];
    }
};

triangulation.setPoints(pointGetter, totalNumPoints);
```

Note that the points would still need to be random-accessible, which means that each point must have an unique index, and from an index, you should be able to get the corresponding point in constant time.
If the points are not random accessible, then you do have to create a copy of them (or create a mapping that is random accessible, by e.g. creating a vector of pointers to the points).

Let me know if this would work for you, I'll probably implement this in the next days.

Edit: after taking a look at your code, I think this isn't exactly the problem - it looks like you have a lot of points, and you don't want to include them all in the triangulation, you want to explicitly define every point index, even for steiner points (so unreferenced points should not be be part of the triangulation).
I'll think about how this could be implemented.

**Comment by starseeker** [comment]
You're correct - one of the use cases is to re-triangulate a small subset of a large mesh, and in that situation what we (try) to do is define an "outer" polygon and interior steiner points for the area of interest that is a subset of the larger mesh.  In that case the thought would be to just reuse the "parent" mesh's point set rather than having to make a new points array and re-index the polygon definitions for just the subset.

With poly2tri we're just duplicating everything in terms of their types, so it's not a big deal if we need to do the same thing here - I just got intrigued by the possibility of being able to avoid extra copies of our data. 

I'm still getting things set up to feed in our data to detria (not working yet, just got something to compile last evening but I've not gotten it setting up correctly) - one thing I may be doing wrong there is setting the points after I'm adding the outer and hole polygons.  Do I need to do the setPoints call first, and then set the loops up?  (Not a problem if that's needed, I was just assigning them as I defined them for convenience.)

Also, is there a simple way to get a count of all "inner" triangles produced by a triangulation?  Right now I'm just iterating over the result and incrementing a counter, but at least internally it looks like there's a size() value that corresponds to the triangle count.  Would it be OK to add a method (if it's not already there and I missed it) to get that info?  Something like tri.InnerTriCount() and/or tri.HoleTriCount()?

**Comment by starseeker** [comment]
Update - got detria working in our code.  Preliminary results looking good!

**Comment by starseeker** [comment]
Oh, one other question I had - how deeply does detria depend on C++20 features?  Would it be practical to use only C++17?  Mostly asking because it can have an impact in some environments using older compilers.

**Comment by Kimbatt** [comment]
> Update - got detria working in our code. Preliminary results looking good!

That's great to hear!

> Oh, one other question I had - how deeply does detria depend on C++20 features? Would it be practical to use only C++17? Mostly asking because it can have an impact in some environments using older compilers.

I think it should work fine with C++17, the only thing that is different is the use of `[[likely]]` and `[[unlikely]]` attributes, which were standardized with C++20 (before that, those were compiler-specific attributes, like `__builtin_expect` in GCC)

**Comment by starseeker** [comment]
I gave a C++17 compile a shot, and got the following errors:
https://brlcad.org/~starseeker/detria_cpp17_errors.txt

**Comment by Kimbatt** [comment]
I've updated the code to work with C++17, I remembered that it just worked before, I guess I was wrong :D

Also, I've added "point getters", which allow a bit more flexibility with setting the input points:
```cpp
auto pointGetter = [&](Idx idx) -> const Point&
{
    // Retrieve point from an index; 0 <= idx < numPoints
    return ...;
};

struct Config : detria::DefaultTriangulationConfig<Point, Idx>
{
    using PointGetter = decltype(pointGetter);
};

detria::Triangulation<Point, Idx, Config> tri;
tri.setPointGetter(pointGetter, numPoints);
...
```

I couldn't implement the version with fully sparse indexing, since the topology class stores the vertices (and other primitives) in contiguous collections, which means that they are indexed from zero up to `size`. And since we need to be able to retrieve the topology vertex from an input vertex (and also the other way around), we'd need to use a hashmap or something to map from the original index to the topology vertex index (which would probably be slower, and use more memory).

**Comment by starseeker** [comment]
Awesome - thank you!  Confirmed the updated version builds in C++17 mode with our code.  Thank you for adding the "point getters" - I'll have to think about how to organize things on our end to take advantage in situations where we can do so.

I'll close this out rather than tacking on more question to the thread :-)

**Comment by Kimbatt** [comment]
Alright, if you have any questions, feel free to ask!
I'll also update the documentation soon.
