### ISSUE TITLE
Preferred format for submission of example "problem" inputs?

### ISSUE THREAD

**Issue by starseeker** [Kimbatt/detria#4]
I should hasten to say I don't have any "problematic" examples yet (still in earliest phase of testing), but if in testing I should come across an input that appears to cause some form of problem, does the detria project have a preferred input format to use for generating test cases to submit?

**Comment by Kimbatt** [comment]
Currently, the file format used is described here: https://github.com/Kimbatt/detria/blob/master/src/main.cpp#L261 (readFile function)
It would be a good idea to add some kind of "dump the current data as a test file" functionality to the triangulation class, so I'll probably do that soon too :D

**Comment by Kimbatt** [comment]
I've added a function to do this: `generateDebugFile` (member function of the triangulation)
This will return a text representation of the current triangulation data, which then can be saved to a file.
